version: '3'
services:
  mysql:
    image: mysql
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: manager
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password
  app:
      build:
        context: ./
        dockerfile: Dockerfile-php
      container_name: app
      working_dir: /var/www
      volumes:
        - ./:/var/www/
  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/usr/share/nginx/html
    ports:
      - 8080:80
    command: [nginx-debug, '-g', 'daemon off;']
